# version: '3.8'

services:
  auth:
    image: auth-service:latest
    container_name: auth-service
    network_mode: host
    #    volumes:
    #      - ./database:/app/dist/database/sqlite/data.sqlite
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=asdad
    restart: unless-stopped

  tournament:
    image: tournament-service:latest
    container_name: tournament-service
    network_mode: host
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - auth