name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci-check:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [auth, tournament]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Test Docker Build
      run: docker build ./${{ matrix.service }} -t test-image